"""Conversation history compression.

Naive history blows the input token bill linearly with conversation length.
This module keeps the last K turns verbatim and replaces older turns with a
single short summary line, generated by Haiku and cached in Redis so the same
conversation doesn't get re-summarised on every turn."""

from __future__ import annotations

import hashlib
import json
from typing import Optional
from uuid import UUID

import redis.asyncio as aioredis
import structlog

from eshopeo.config import Settings

logger = structlog.get_logger(__name__)

_KEEP_LAST = 4                   # full turns at the tail
_SUMMARISE_AFTER = 6             # only build a summary once history >= this
_SUMMARY_MODEL_KEY = "claude-haiku-4-5"
_SUMMARY_TTL_S = 24 * 60 * 60


class HistoryCompressor:
    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._r = aioredis.from_url(str(settings.redis_url), decode_responses=True)

    async def aclose(self) -> None:
        await self._r.aclose()

    async def compress(
        self,
        conversation_id: UUID,
        messages: list[dict],
    ) -> list[dict]:
        """Returns a compressed message list ready to send to the LLM.

        - if len(messages) <= _SUMMARISE_AFTER: return as-is
        - else: prepend a single 'system summary' message of older turns + keep last K verbatim
        """
        if len(messages) <= _SUMMARISE_AFTER:
            return messages

        head = messages[:-_KEEP_LAST]
        tail = messages[-_KEEP_LAST:]

        cache_key = self._cache_key(conversation_id, head)
        cached = await self._r.get(cache_key)
        if cached:
            summary = cached
        else:
            summary = await self._summarise(head)
            if summary:
                await self._r.setex(cache_key, _SUMMARY_TTL_S, summary)

        if not summary:
            return tail  # safer to truncate than blow tokens

        return [
            {"role": "user", "content": f"[Conversation summary so far]\n{summary}"},
            {"role": "assistant", "content": "Got it — continuing from there."},
            *tail,
        ]

    async def _summarise(self, head: list[dict]) -> Optional[str]:
        try:
            import anthropic
        except ImportError:
            return None
        client = anthropic.AsyncAnthropic(
            api_key=self._settings.anthropic_api_key.get_secret_value()
        )
        joined = "\n".join(
            f"{m.get('role', 'user').upper()}: {m.get('content', '')[:500]}" for m in head
        )
        prompt = (
            "Summarise this customer-assistant exchange in 2-3 short bullet points. "
            "Capture the customer's preferences, anything they're shopping for, and any decisions made. "
            "Be terse — this is for compressing context, not for human reading.\n\n" + joined
        )
        try:
            resp = await client.messages.create(
                model=_SUMMARY_MODEL_KEY,
                max_tokens=200,
                system="You compress chat histories into terse bullet summaries.",
                messages=[{"role": "user", "content": prompt}],
            )
            return resp.content[0].text.strip()
        except Exception as e:  # noqa: BLE001
            logger.warning("history_summary_failed", error=str(e))
            return None

    @staticmethod
    def _cache_key(conversation_id: UUID, head: list[dict]) -> str:
        digest = hashlib.sha256(
            json.dumps([m.get("content", "") for m in head], sort_keys=True).encode()
        ).hexdigest()[:16]
        return f"hxhist:{conversation_id}:{digest}"
