<?php
defined( 'ABSPATH' ) || exit;

/**
 * Eshopeo_Product_Faq
 *
 * Registers the [eshopeo_product_faq] shortcode.
 *
 * Calls GET /v1/widget/product-faq/{platform_id} and renders an accordion FAQ
 * block.  FAQs are generated by Claude on the first call and cached server-side.
 */
class Eshopeo_Product_Faq {

    public static function init(): void {
        add_shortcode( 'eshopeo_product_faq', [ self::class, 'shortcode' ] );
        add_action( 'wp_head', [ self::class, 'inline_styles' ] );
    }

    public static function inline_styles(): void {
        ?>
        <style>
        .hx-pfaq { margin: 24px 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
        .hx-pfaq h3 { font-size: 18px; font-weight: 700; color: #1C1C1E; margin: 0 0 14px; }
        .hx-pfaq-item { border: 1px solid rgba(0,0,0,.08); border-radius: 12px; margin-bottom: 8px; overflow: hidden; }
        .hx-pfaq-q { display: flex; align-items: center; justify-content: space-between; gap: 8px;
            padding: 14px 16px; cursor: pointer; background: #fff; font-size: 14px; font-weight: 600;
            color: #1C1C1E; user-select: none; }
        .hx-pfaq-q:hover { background: rgba(124,58,237,.04); }
        .hx-pfaq-icon { flex-shrink: 0; width: 20px; height: 20px; border-radius: 50%;
            background: linear-gradient(135deg,#7C3AED,#4F46E5); color: #fff;
            display: flex; align-items: center; justify-content: center; font-size: 14px; line-height: 1;
            transition: transform .2s; }
        .hx-pfaq-item.open .hx-pfaq-icon { transform: rotate(45deg); }
        .hx-pfaq-a { display: none; padding: 0 16px 14px; font-size: 13.5px; color: #3C3C43; line-height: 1.6; }
        .hx-pfaq-item.open .hx-pfaq-a { display: block; }
        .hx-pfaq-loading { color: #8E8E93; font-size: 13px; padding: 8px 0; }
        </style>
        <script>
        document.addEventListener('click', function(e) {
            var q = e.target.closest('.hx-pfaq-q');
            if (!q) return;
            q.closest('.hx-pfaq-item').classList.toggle('open');
        });
        </script>
        <?php
    }

    public static function shortcode( array $atts ): string {
        if ( ! get_option( 'eshopeo_widget_enabled', 0 ) ) return '';

        $public_key = get_option( 'eshopeo_public_key', '' );
        $api_url    = rtrim( get_option( 'eshopeo_api_url', '' ), '/' );
        if ( ! $public_key || ! $api_url ) return '';

        $atts = shortcode_atts( [ 'product_id' => '' ], $atts, 'eshopeo_product_faq' );

        /* Resolve product ID */
        $wc_product_id = ! empty( $atts['product_id'] ) ? (int) $atts['product_id'] : get_the_ID();
        if ( ! $wc_product_id ) return '';
        $product = wc_get_product( $wc_product_id );
        if ( ! $product instanceof WC_Product ) return '';

        $platform_id = (string) $product->get_id();

        /* Fetch FAQs from eShopeo API (server-side, cached by eShopeo) */
        $endpoint = $api_url . '/v1/widget/product-faq/' . rawurlencode( $platform_id );
        $response = wp_remote_get( $endpoint, [
            'timeout' => 8,
            'headers' => [ 'X-eShopeo-Tenant-Key' => $public_key ],
        ] );

        if ( is_wp_error( $response ) || wp_remote_retrieve_response_code( $response ) !== 200 ) {
            return '';
        }

        $body = json_decode( wp_remote_retrieve_body( $response ), true );
        $faqs = $body['faqs'] ?? [];
        if ( empty( $faqs ) ) return '';

        ob_start();
        ?>
        <div class="hx-pfaq">
            <h3>Frequently Asked Questions</h3>
            <?php foreach ( $faqs as $faq ) : ?>
            <div class="hx-pfaq-item">
                <div class="hx-pfaq-q">
                    <span><?php echo esc_html( $faq['question'] ?? '' ); ?></span>
                    <span class="hx-pfaq-icon" aria-hidden="true">+</span>
                </div>
                <div class="hx-pfaq-a"><?php echo esc_html( $faq['answer'] ?? '' ); ?></div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php
        return ob_get_clean();
    }
}
